server:
    port: 8081
    servlet:
        contextPath: /fseapidmz
        
client:        
    ssl:
        key-store-type: PKCS12
        key-alias: fsescibinternetdevv1
        key-store: FSESCIBInternetDevV1.p12
        key-store-password: 123456
        trust-store-type: PKCS12
        trust-store: tsfsescibintranetdevv1.p12
        trust-store-password: 123456

logging:
    level:
        root: DEBUG
        org.springframework.web: ERROR
        org.apache.zookeeper: ERROR
        org.apache.kafka: ERROR

    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

base:
    jwt:
        skewTime: 10
    dmz:
        # La url deberá ser la siguiente: https://pkm-interbck.scib.dev.corp pero para pruebas usamos intranet
        pkm: 
            uri: https://localhost:8443
    intra:
        sts:
            uri: https://localhost:8443
            user: 1
            password: 1
        pkm:
            uri: https://localhost:8443
        fse: 
            uri: https://localhost:8443

spring:
  cache:
    cache-names: PUBLICKEYS
    caffeine:
      spec: maximumSize=500, expireAfterAccess=1m
